### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Chenxy-1999** [apecodex/yibanAutoSgin#4]
import util
  File "/home/lighthouse/yibanAutoSgin/util.py", line 21
    def html_format(date, postContext, url, signStr)->str:
                                                    ^
SyntaxError: invalid syntax

**Comment by apecodex** [comment]
python 版本要求3.8以上

**Comment by Chenxy-1999** [comment]
如何多账号呢

**Comment by apecodex** [comment]
> 如何多账号呢

config.py 文件中，最上面写了模板

**Comment by Chenxy-1999** [comment]
谢谢
