### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by ghost** [apecodex/yibanAutoSgin#6]
Traceback (most recent call last):
  File "/root/yibanAutoSgin/main.py", line 67, in <module>
    result = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time())) + "表单提交失败！请检查\n")
TypeError: can only concatenate tuple (not "str") to tuple
请问这是什么问题

**Comment by apecodex** [comment]
> 回溯（最近一次调用）： 文件“/root/yibanAutoSgin/main.py”，第 67 行， 结果 = time.strftime("%Y-%m-%d %H:%M:%S", time .localtime(int(time.time())) + "表单提交失败！请检查\n") TypeError: can only concatenate tuple (not "str") to tuple 请问这是什么问题

好像是他把签到请求的参数也变成加密格式了

**Comment by Chenxy-1999** [comment]
好的，那就这样吧
