### ISSUE TITLE
现在还可以使用吗？

### ISSUE THREAD

**Issue by bylengfeng** [apecodex/yibanAutoSgin#7]
现在还可以使用吗？抓包发现好多字段加密了

**Comment by apecodex** [comment]
可以的，你把表单id换成你们的就可以用了

**Comment by apecodex** [comment]
> 现在还可以使用吗？抓包发现好多字段加密了

可以的，你把表单id换成你们的就可以用了

**Comment by bylengfeng** [comment]
> > 现在还可以使用吗？抓包发现好多字段加密了
> 
> 可以的，你把表单id换成你们的就可以用了

好的
